service: lambda-crud-usuarios
frameworkVersion: '3'

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      docker: true

provider:
  name: aws
  runtime: nodejs16.x
  apiGateway: 
    apiKeys:
      - lambda-crud-usuarios-apikey
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/usersTable

functions:
  find-user:
    handler: src/application/find.handler
    package:
      patterns:
        - '!src/test/**'
        - 'src/application/find.ts'
        - 'src/domain/**'
        - 'src/infraestructure/**'
    events:
      - http:
          private: true
          path: users/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  create-user:
    handler: src/application/create.handler
    package:
      patterns:
        - '!src/test/**'
        - 'src/application/create.ts'
        - 'src/domain/**'
        - 'src/infraestructure/**'
    events:
      - http:
          path: users
          method: POST
          request:
            schemas:
              appication/json: ${file(src/domain/schemas/user.schema.json)}
  update-user:
    handler: src/application/update.handler
    package:
      patterns:
        - '!src/test/**'
        - 'src/application/update.ts'
        - 'src/domain/**'
        - 'src/infraestructure/**'
    events:
      - http:
          private: true
          path: users/{id}
          method: PATCH
          request:
            parameters:
              paths:
                id: true
            schemas:
              appication/json: ${file(src/domain/schemas/user.schema.json)}
  delete-user:
    handler: src/application/delete.handler
    package:
      patterns:
        - '!src/test/**'
        - 'src/application/delete.ts'
        - 'src/domain/**'
        - 'src/infraestructure/**'
    events:
      - http:
          private: true
          path: users/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true
  delete-user-py:
    handler: src/application/delete-py.handler
    package:
      patterns:
        - '!src/test/**'
        - 'src/application/delete-py.py'
    runtime: python3.9
    environment:
      VIRTUAL_ENV_PATH: ./sls_test_py/bin/python
    events:
      - http:
          private: true
          path: users/py/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline

package:
  individually: true
  patterns:
    - "!*/**"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
